# Generated by Django 2.2 on 2021-01-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210120_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='customer_address',
            field=models.CharField(default='Null', max_length=120),
        ),
    ]
